### ISSUE TITLE
Create a working search page

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#118]
Update: we already have username+teamname search, via the rankings table. No need for a new search page (and making one is just reinventing the wheel). Instead, let's fully remove old code!

~deprecated earlier, see #65 and #115
Would be cool to have 
To be clear: I don't know what this search page did. You can probably reconstruct it though. Then fix it.
Don't tackle this if it doesn't seem worth it~

**Comment by j-mao** [comment]
What is this search bar? Don't we already have a search bar on the Rankings page?
