### ISSUE TITLE
Create a public user page

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#19]
Similar to the team-info page we have -- a page with info for each user. (Not sure what might go on here / what's could be considered public)

A couple reasons why:
So that users can individually advertise their own info. (bio, links to other websites like personal website or LinkedIn or github or whatevs)
So that users can be on multiple teams across multiple competitions. Handy if we make a all-version scrimmaging website

**note that this user page should be agnostic to episode!! Feel free to ask for help/clarification about what this means, or how to implement**

**Comment by lowtorola** [comment]
Thinking that the inital public-facing user page will consist of an updated userCard and the user's teamCard below it. This will provide basic info about the user while leaving room for future feature-adding.
