### ISSUE TITLE
Clean up repeated avatar logic

### ISSUE THREAD

**Issue by gaurav-arya** [battlecode/galaxy#302]
There is repeated logic across the `Team` and `User` models for e.g. forming a public avatar URL. It would be nice to abstract these away

**Comment by varuntumbe** [comment]
Hi sir, 

Is these open issues only for MIT folks or is it for everyone to contribute to?

**Comment by j-mao** [comment]
I think this is as cleaned-up as can be, to allow them to be changed independently of each other.
