### ISSUE TITLE
stylistic changes to UI and rewrite content to be clearer

### ISSUE THREAD

**Issue by acrantel** [battlecode/galaxy#322]
TODO:

- [ ] Update the flag logo to our new battlecode 2023 symbol created by maggie
- [ ] Update battlecode 2023 font to font used on homepage (https://fonts.adobe.com/fonts/josefin-sans)
- [ ] Revise the text on the battlecode dashboard to be clearer

**Comment by n8kim1** [comment]
@acrantel is this done? i think it is?
feel free to close

**Comment by n8kim1** [comment]
done in #325!
