### ISSUE TITLE
Frontend nondeterministically displays multiple submissions for the same tournament

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#33]
(from Arvid)
https://github.com/battlecode/battlecode20/issues/385

This will probably not be a thing once #78 is addressed (since it calls for a full rewrite) but idk for sure

**Comment by gaurav-arya** [comment]
Example?

**Comment by j-mao** [comment]
I think this was from an old rendition of the frontend. Since this part got completely re-written, this issue just doesn't exist anymore.

**Comment by gaurav-arya** [comment]
All right, closing this then
