### ISSUE TITLE
Show list of all scrimmages in queue and history

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#339]
paging @j-mao if you wanna edit this description to fully flesh out thoughts

**Comment by j-mao** [comment]
Everyone wants to know how long the queue is! We want to know how other teams are doing! Tired after writing lots of code and want to take a break? Check out the queue :')

There's already an API endpoint that returns the entire queue, with secret data redacted. Let's render this into a webpage.

**Comment by j-mao** [comment]
This is important as a scrimmage ranking integrity measure.
