### ISSUE TITLE
Create endpoint that returns an arbitrary team's timestamp-vs-elo-ranking

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#371]
For display in frontend's team performance charts.

Compile the data in backend. Return some mapping of timestamps-to-elo. The most straightforward one is, eg, for each scrimmage, return the scrimmage timestamp and the team's rating after. (Try to return just this data to cut down on size!)

**Comment by gaurav-arya** [comment]
Wait, why does this need a new endpoint? Isn't the rating history already accessible through the `scrimmage` endpoint? One just needs to ignore the unranked matches. @n8kim1 @j-mao

**Comment by gaurav-arya** [comment]
I see, you want to remove all the redundant information in the output and not paginate, I guess that makes sense. @lowtorola in that case, this would look a lot like the existing scrimmage endpoint, except that it would always be for a single particular team, it is not paginated, and the serializer should be modified to extract the timestamp (easy) and the team's new rating (a bit harder: that should be extracted from the appropriate match participant object of the scrimmage), with unranked scrimmages filtered out.
