### ISSUE TITLE
Host visualizer and show replays

### ISSUE THREAD

**Issue by gaurav-arya** [battlecode/galaxy#433]
Replay links from scrimmage history page should be opened in the visualizer and play correctly.

**Comment by j-mao** [comment]
Visualizer will be available at https://releases.battlecode.org/client/battlecode23/1.0.0/visualizer.html, where:

- `battlecode23` corresponds with the name of the Maven artifact, which for engine-side legacy reasons is not the episode name. We'll add this to the Siarnaq episode API.
- `1.0.0` corresponds with the release version.

**Comment by j-mao** [comment]
To be clear: the only reason this link doesn't work right now is because engine hasn't got any releases yet. The code for this has already been written; the link will start working immediately as soon as engine creates a release. We'll just need to write the code to hook into this.

**Comment by gaurav-arya** [comment]
OK, but since we need a backend change for this I don't think we can incorporate the correct link into #435, just leave this as a critical issue?

**Comment by j-mao** [comment]
Yep! Backend change was done in #446 so this is now unblocked.

**Comment by n8kim1** [comment]
one thing: make sure to dynamically get version number from backend!
it should be rattling around in episode_info
use the public one

**Comment by n8kim1** [comment]
closed by #465
