### ISSUE TITLE
If first tour is before game release, then countdown displays first tour, not game release

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#434]
....which is odd...

Theoretically, game release shouldn't be before first tour anyways, so the backend shouldn't ever exist in this state, and so frontend shouldn't be odd. But it's a strange error propagation anyways.

**Comment by j-mao** [comment]
What's the specific configuration? I find this quite odd, because:
- If game release is in the future, then the frontend should display nothing at all about the episode
- If game release is in the past, then the first tour is also in the past, so the frontend should display nothing about it either.

**Comment by n8kim1** [comment]
registration in past, tour in future, game release in farther future 

(note reg already open)

**Comment by j-mao** [comment]
Oh yep i see -- my bad. I don't think it's enforceable as a database-level constraint… do we want to enforce this programmatically, or just make frontend handle it?

**Comment by n8kim1** [comment]
good point
either is fine — maybe just add “backend” label as well and save furhrrr
discussion for later?

**Comment by j-mao** [comment]
Cannot reproduce. Have you tried this while not logged in as a user with staff privileges?

**Comment by j-mao** [comment]
Please re-open if this is still an issue.

**Comment by n8kim1** [comment]
yup, it's cuz I was logged in as staff. In fact, as staff, the behavior seems expected/good -- the game is always released to staff anyways.

For nonstaff this bug doesn't appear!
