### ISSUE TITLE
Allow only admins to see match / scrimmage logs

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#436]
Also, should change unit-tests of serialization. Don't `del data["logs"]`, and actually put logs into the one test of admin exposure.

(Would be cool to expose them in backend admin panel, if not done already)

Also, then, change frontend to not include the columns for logs in scrimmages

**Comment by j-mao** [comment]
Already available on backend panel. Not exposed at all via API and frontend. Good to close?
