### ISSUE TITLE
Investigate machine sizing vs runtime tradeoff

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#456]
@j-mao pls triage and fill deets as needed

**Comment by j-mao** [comment]
Saturn! Machines larger –> games faster? But how much larger? Investigate.

**Comment by j-mao** [comment]
## Experiment

Ran experiments with 6 machine types: `e2-highmem-2`, `e2-standard-4`, `n1-highmem-2`, `n1-standard-4`, `t2d-standard-1`, `t2d-standard-2`.

Match: battlecode22 examplefuncsplayer v examplefuncsplayer on maptestsmall.

Results (all measurements in seconds, rounded to nearest integer):

Machine type | Build time (cold) | Build time (warm) | Match 1 | Match 2 | Match 3 | Match (best)
--- | --: | --: | --: | --: | --: | --:
e2-highmem-2 | 99 | 8 | 71 | 71 | 71 | 71
e2-standard-4 | 73 | 6 | 60 | 63 | 62 | 60
n1-highmem-2 | 102 | 8 | 89 | 77 | 75 | 75
n1-standard-4 | 74 | 5 | 71 | 73 | 70 | 70
t2d-standard-1 | 85 | 6 | 41 | 41 | 39 | 39
t2d-standard-2 | 48 | 4 | 38 | 37 | 37 | 37

## Conclusions and further discussion

For match running, the t2d series appears to be the clear winner. However, it doesn't have a highmem type… does `t2d-standard-1` come with enough RAM to run a whole game? If not -- can we get away with allocating some swap space?

For compiling: seems to matter less, especially if warm (eg. around submission deadlines). Would be good to optimize the cold build-time too, but let's think about it more. Inclined to stick with t2d for consistency though.

## Source code

Driver `experiment.sh`
```bash
#!/bin/bash

set -exo pipefail

types=(
  e2-highmem-2
  e2-standard-4
  n1-highmem-2
  n1-standard-4
  t2d-standard-1
  t2d-standard-2
)

for t in "${types[@]}"; do
  gcloud compute instances create jerrym-experiment-$t \
    --image-project=ubuntu-os-cloud \
    --image-family=ubuntu-2204-lts \
    --metadata-from-file=startup-script=run.sh \
    --machine-type=$t \
    --zone=us-central1-a \
    --network-interface=network-tier=PREMIUM,subnet=default \
    --metadata=enable-guest-attributes=TRUE
done
```

File `run.sh`, to be injected on each GCE machine
```bash
#!/bin/bash

set -exo pipefail

trap "sudo /sbin/shutdown -h" EXIT

sudo apt-get update
sudo apt-get install -y openjdk-8-jdk

mkdir -p /work && cd /work
{
  git clone https://github.com/battlecode/battlecode22-scaffold
  (cd battlecode22-scaffold && ./gradlew build && rm -rf build && ./gradlew build)
   for i in {1..3}; do
     time (cd battlecode22-scaffold && ./gradlew run -PoutputVerbose=false)
   done
} > logs

curl -X PUT --data "`cat logs`" http://metadata.google.internal/computeMetadata/v1/instance/guest-attributes/experiment/logs -H "Metadata-Flavor: Google"
```

**Comment by j-mao** [comment]
Re-running across instances sizes in the t2d series.

Machine type | Build time (cold) | Build time (warm) | Match 1 | Match 2 | Match 3 | Match (best)
--- | --: | --: | --: | --: | --: | --:
t2d-standard-1 | 99 | 8 | 49 | 50 | 48 | 48
t2d-standard-2 | 50 | 4 | 38 | 42 | 43 | 38
t2d-standard-4 | 42 | 3 | 44 | 42 | 42 | 42
t2d-standard-8 | 41 | 3 | 41 | 42 | 41 | 41

Biggest improvement in cold-start runtime is when going from 1 to 2 vCPUs; everything else is not significant. Conclusion: we want to use at least 2 vCPUs per instance. Only thing left to check is how much RAM we need to run a full game.

**Comment by j-mao** [comment]
I'm going to estimate that 8GiB is good enough for now, and we can increase it later if games crash.
