### ISSUE TITLE
De-duplicate code for displaying Saturn status for scrimmages and submissions

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#460]

**Comment by j-mao** [comment]
Unsure it's a good idea to dedupe. `RUN` should be interpreted as "verifying" in submissions and "running" in matches.

**Comment by n8kim1** [comment]
there's also a difference in what "OK!" means -- for matches, it means that it's run; in submissions, you have to look at "accepted" as well for compilation success/failure

given these differences, and the fact that it only occurs twice...we can keep things simple. (De-duped code would have to have some nontrivial machinery)
