### ISSUE TITLE
Port various website manuals/writeups into one source; update them; remove dead links

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#49]
Clean up the content of each of these gdocs:
- [x] https://docs.google.com/document/d/1I1DyXKnjYqMY2RY3Kwl7D4bzvwbsxeTkF3U73XX6sdc/edit#
- [x] https://docs.google.com/document/d/1PuuKfxVCeaoqOXoas8dkjHuJsovHFPZjSe6MMGVVKsQ/edit#
- [x] https://docs.google.com/document/d/1xEwITlKRpn4Vd8iWC4l86eQcNpOCUOYKM644vBQKL-s/edit#
- [x] https://docs.google.com/document/d/16bxwyXN5ZFv4aPFMoNAWLVbaKS2S1D_Chk2lK9RvFJc/edit

They each have their own instructions about webinfra, both on the technical and logistics sides. **Consolidate them: They should really be consolidated into the repo readmes and the main gdoc**, so that we don't have to hold on to invalid/obsolete instructions, and so that we don't have to poke around odd places. If a google doc still exists, it should be recursively pointed to and from, via the main google doc. This makes sure everything is discoverable and connected
Also, **remove any content that is incorrect, out-of-date-etc**
Feel free to write up more (and revise) as you see fit. This part isn't a big deal though, and probably not worth the time

finally, for each of these docs:
- [x] https://docs.google.com/document/d/1AlunZNJ9xJ8nHBAiGBR3P-0IbkD9jxN39KtuM2v4oYs/edit
- [x] https://docs.google.com/document/d/1wzxFF308kQoPed11UQvRbzyHz9rykQd69IcVms4uwa4/edit
- [x] https://docs.google.com/document/d/16bxwyXN5ZFv4aPFMoNAWLVbaKS2S1D_Chk2lK9RvFJc/edit

**Go through our google drive, and check for files everywhere that touch on webinfra; they might be in multiple folders. Unify to one folder. Then, clean redundant / duped or old things.** 

Critical cuz it's important. But: _Low-priority_ since new devs have been onboarded, and we all know what we're doing for now. However, after IAP, this would be great to handle.

**Comment by j-mao** [comment]
It looks like a lot of the information in those documents are about deploy, etc. (except for the 2nd document, which I think we should never put on GH). How much of these documents are still relevant?

**Comment by n8kim1** [comment]
good q -- this seems like an issue we should tackle collectively? and decide then
