### ISSUE TITLE
Create a warning abt creating tournament rounds in admin panel

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#531]
On second thought you probably shouldn't create them directly unless Challonge is breaking and you absolutely need to.

~Need to expose "tournament" in the page, as (best) a dropdown box that must not be empty
Isn't critical cuz at least you can create a tournament round from the tournament page. Still, that's a workaround, not the solution~

**Comment by j-mao** [comment]
Oops

**Comment by j-mao** [comment]
Is an oversight that the field is missing from admin. But also, you should never create it on the admin page.

**Comment by n8kim1** [comment]
true, will edit desc and title

**Comment by j-mao** [comment]
Warning seems unnecessary. It's nothing more than "please don't add unnecessary rows to the table".
