### ISSUE TITLE
Clean up tournament runner code

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#549]
#166 will create a tour runner that works, altho it might have bad code, be slow, or _be hard to use_. This is fine cuz deadlines...but for later it will be bad. Clean!!

**Make sure to ctrl-f "#549"!!!!**

**Comment by j-mao** [comment]
Per our offline discussions, unsure what makes it hard to use if we implement the specs we decided on?

**Comment by n8kim1** [comment]
eg uninformative error messages, doscstrings/option names, uninformative http errors
mainly cuz im lazy
