### ISSUE TITLE
Remove the "seconds" part of the submission deadline time (aka display 7:00:30 as 7:00)

### ISSUE THREAD

**Issue by acrantel** [battlecode/galaxy#571]
# Description

In the homepage of the competitor dashboard, we should remove the seconds part of the submission deadline time. This is so competitors don't accidentally interpret 7:00:30pm as 7:30pm
![image](https://user-images.githubusercontent.com/40174697/212765322-003d22a6-8023-4565-850e-98c584917579.png)

**Comment by n8kim1** [comment]
note: pls **truncate** (or round down, but those terms are equivalent for nonnegative numbers) 
Don't round up!
