### ISSUE TITLE
For scrimmage object, make unranked matches not be in the chain of previous_participation

### ISSUE THREAD

**Issue by n8kim1** [battlecode/galaxy#576]
Allows for easy deletion of unranked matches, which is _great_ for tour runner. 
With this, you should probably consider making `is_ranked` readonly in the admin panel??

**Comment by j-mao** [comment]
No, I don't think this is valid. It is necessary in order to get the rating of participants immediately prior to the match that ran.

Open to thinking of alternatives, but this is not viable.
