### ISSUE TITLE
Improve Rating History/Scrimmaging Record Performance

### ISSUE THREAD

**Issue by acrantel** [battlecode/galaxy#826]
Take a look at this pull request's code to find a more efficient way to compute rating history via querysets / subqueries
https://github.com/battlecode/galaxy/pull/558

**Comment by lowtorola** [comment]
For a bit of context on how bad my first pass implementation was, here's the current hook for getting the top 10 teams' rating histories:
![image](https://github.com/user-attachments/assets/2be34288-e8a2-4624-a3ef-e02bfdd32cb5)
We absolutely need a separate endpoint that does this all in a django query and returns the rating history for the top 10... then probably revert the API to only take a single team id for the regular case? We can discuss further
